name: nlpfuzzer
channels:
  - conda-forge
  - default
dependencies:
  - python=3.7
  - pip=20.3.4
  - numpy=1.19.5
  - cudatoolkit=10.2.89
  - scikit-learn=0.24.1
  - matplotlib=3.4.1
  - pip:
    - annoy==1.17.0
    - tensorflow==2.4.1
    - tensorflow-hub==0.11.0
    - tensorflow-datasets==4.2.0